spring:
  profiles: default
  thymeleaf:
      cache: false  
datasource:
  master:
      driver-class-name: "com.mysql.jdbc.Driver"
      url: "jdbc:mysql://localhost:3306/dlight?autoReconnect=true&useUnicode=true&characterEncoding=utf8"
      user-name: "root"
      password: "Mace0891"
      initial-size: 10
      max-active: 10
      max-idle: 10
      min-idle: 10
      max-wait: 3000
